# Generated by Django 3.0 on 2019-12-04 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('start_at', models.DateTimeField(verbose_name='start at')),
                ('finish_at', models.DateTimeField(verbose_name='finish at')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.City', verbose_name='city')),
            ],
            options={
                'db_table': 'events_event',
            },
        ),
    ]
