# Generated by Django 3.0 on 2019-12-06 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
        ('events', '0003_event_event_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_online',
            field=models.BooleanField(default=False, verbose_name='event online'),
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.City', verbose_name='city'),
        ),
    ]
