FROM python:3.6-slim-stretch

# Env vars
ENV PYTHONUNBUFFERED 1

RUN apt update
RUN apt install -y cron
RUN apt install -y locales-all
RUN apt install -y chromium

RUN cp /usr/bin/chromium /usr/bin/chromium-browser
# Create app directory
WORKDIR /usr/src/app
COPY . .

# Make executable scripts
RUN cp ./scripts/cron.sh /usr/local/bin/run-cron
RUN cp ./scripts/runserver.sh /usr/local/bin/run-server
RUN cp ./scripts/test.sh /usr/local/bin/run-test
RUN cp ./scripts/deploy.sh /usr/local/bin/run-deploy

CMD run-cron